version: '3.8'
name: artyom-itmo

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    ports:
      - "3031:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin