version: '3.8'
name: artyom-itmo

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped